### ISSUE TITLE
server connect - pump Status with pump on hangs

### ISSUE THREAD

**Issue by thetreerat** [thetreerat/WaterPump#3]
repl console output
Pump - 22: added Pump Status to loop <bound_method>
Traceback (most recent call last):
  File "main.py", line 79, in <module>
  File "lib/uasyncio/core.py", line 265, in run_forever
  File "lib/uasyncio/core.py", line 181, in run_forever
  File "WaterPumps/pumps.py", line 106, in pumpStatus
TypeError: function takes 2 positional arguments but 1 were given

**Comment by thetreerat** [comment]
Fixed in a7851cb
